server:
  port: 27997
spring:
  cloud:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
      bucket: xxnjdgoss
      sms:
        callbackUrl: http://test.dev.esandcloud.com
        channel: 1
        time: 1
        appcode:
    # 注册中心nacos地址
    nacos:
      discovery:
        server-addr: 192.168.100.26:8848