server:
  port: 27997
spring:
  cloud:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
      bucket: xxnjdgoss
      sms:
        callbackUrl: http://test.dev.esandcloud.com
        channel: 1
        time: 1
        appcode:
    # 注册中心nacos地址
    nacos:
      discovery:
        server-addr: 192.168.100.26:8848

# Dubbo 配置项，对应 DubboConfigurationProperties 类
dubbo:
  scan:
    base-packages: io.xxnjdg.mall.third.party.service.impl # 指定 Dubbo 服务实现类的扫描基准包
  # Dubbo 服务暴露的协议配置，对应 ProtocolConfig Map
  protocols:
    dubbo:
      name: dubbo # 协议名称
      port: -1 # 协议端口，-1 表示自增端口，从 20880 开始
  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry:
    address: spring-cloud://192.168.100.26:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
  cloud:
    subscribed-services: '' # 设置订阅的应用列表，默认为 * 订阅所有应用
  consumer:
    check: false
    timeout: 3000
  provider:
    filter: -exception