server:
  port: 11000
spring:
  application:
    name: xxnjdg-member-service
  datasource:
    url: jdbc:mysql://192.168.100.26:3306/xxnjdg_mall_ums?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 数据库账号
    password: root # 数据库密码
  # 注册中心nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto