server:
  port: 14000
spring:
  application:
    name: xxnjdg-ware-service
  datasource:
    url: jdbc:mysql://192.168.100.26:3306/xxnjdg_mall_wms?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 数据库账号
    password: root # 数据库密码
  # 注册中心nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
# Dubbo 配置项，对应 DubboConfigurationProperties 类
dubbo:
  scan:
    base-packages: io.xxnjdg.mall.ware.service.impl # 指定 Dubbo 服务实现类的扫描基准包
  # Dubbo 服务暴露的协议配置，对应 ProtocolConfig Map
  protocols:
    dubbo:
      name: dubbo # 协议名称
      port: -1 # 协议端口，-1 表示自增端口，从 20880 开始
  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry:
    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
  cloud:
    subscribed-services: '' # 设置订阅的应用列表，默认为 * 订阅所有应用
  consumer:
    check: false
  provider:
    filter: -exception
swagger:
  enable: true # 暂时不去掉
  title: ware子系统
  description: ware子系统
  version: 1.0.0
  base-package: io.xxnjdg.mall.ware.controller