server:
  port: 27996
spring:
  application:
    name: xxnjdg-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: product_route
          uri: lb://xxnjdg-product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://xxnjdg-coupon-service
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://xxnjdg-member-service
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://xxnjdg-order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://xxnjdg-ware-service
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: search_route
          uri: lb://xxnjdg-search-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://xxnjdg-third-party-service
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: gulimall_host_route
          uri: lb://xxnjdg-product-service
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: search_gulimall_host_route
          uri: lb://xxnjdg-search-service
          predicates:
            - Host=search.gulimall.com

        - id: gulimall_auth_route
          uri: lb://xxnjdg-auth-service
          predicates:
            - Host=auth.gulimall.com

      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            max-age: 3600
    # 注册中心nacos地址
    nacos:
      discovery:
        server-addr: 192.168.100.26:8848
